/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Notesful.ui;
import Notesful.db.DBException;
import Notesful.db.DBUtil;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Prise
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        SignupLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        QuestionLabel = new javax.swing.JLabel();
        SignupLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notesful");
        setName("LoginFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 370));
        setResizable(false);

        bg.setBackground(new java.awt.Color(51, 51, 51));
        bg.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        bg.setMinimumSize(new java.awt.Dimension(360, 336));
        bg.setPreferredSize(new java.awt.Dimension(360, 336));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignupLabel.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        SignupLabel.setForeground(new java.awt.Color(255, 255, 255));
        SignupLabel.setText("Login");
        SignupLabel.setMaximumSize(new java.awt.Dimension(180, 62));
        SignupLabel.setMinimumSize(new java.awt.Dimension(180, 62));
        SignupLabel.setPreferredSize(new java.awt.Dimension(180, 62));
        bg.add(SignupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 34, -1, -1));

        LoginButton.setBackground(new java.awt.Color(102, 102, 102));
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        bg.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 234, -1, -1));
        bg.add(UsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 144, 170, -1));

        UsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel.setText("Username:");
        bg.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 124, -1, -1));

        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Password:");
        bg.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 174, -1, -1));
        bg.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 194, 170, -1));

        QuestionLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuestionLabel.setText("Don't have an account? ");
        bg.add(QuestionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        SignupLabel2.setForeground(new java.awt.Color(0, 102, 255));
        SignupLabel2.setText("Signup");
        SignupLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupLabel2MouseClicked(evt);
            }
        });
        bg.add(SignupLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // Get username and password field
        String username = UsernameTextField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        
        if (username.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a username", "Notesful Error",1);
        } else if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a password", "Notesful Error",1);
        } else {
            try {
                String query = "SELECT * FROM note_app WHERE username =? AND password =?";
                Connection connection = DBUtil.getConnection();
                try (PreparedStatement ps = connection.prepareStatement(query)){
                    ps.setString(1, username);
                    ps.setString(2, password);
                    ResultSet rs = ps.executeQuery();
                    if (rs.next())
                    {
                        MainForm mf = new MainForm();
                        mf.setVisible(true);
                        mf.pack();
                        mf.setLocationRelativeTo(null);
                        mf.setDefaultCloseOperation(EXIT_ON_CLOSE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "No Access");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                }
        } catch (DBException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignupLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupLabel2MouseClicked
        SignupForm suf = new SignupForm();
        suf.setVisible(true);
        suf.pack();
        suf.setLocationRelativeTo(null);
        suf.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_SignupLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel QuestionLabel;
    private javax.swing.JLabel SignupLabel;
    private javax.swing.JLabel SignupLabel2;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JPanel bg;
    // End of variables declaration//GEN-END:variables
}
