package Notesful.ui;

import Notesful.db.DBException;
import Notesful.db.DBUtil;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;

public class SignupForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public SignupForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bg = new javax.swing.JPanel();
        SignupLabel = new javax.swing.JLabel();
        SignupButton = new javax.swing.JButton();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        QuestionLabel = new javax.swing.JLabel();
        LoginLabel2 = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notesful");
        setName("SignupFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 375));
        setResizable(false);

        bg.setBackground(new java.awt.Color(51, 51, 51));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignupLabel.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        SignupLabel.setForeground(new java.awt.Color(255, 255, 255));
        SignupLabel.setText("Sign Up");
        bg.add(SignupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        SignupButton.setBackground(new java.awt.Color(102, 102, 102));
        SignupButton.setForeground(new java.awt.Color(255, 255, 255));
        SignupButton.setText("Sign up");
        SignupButton.setBorderPainted(false);
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });
        bg.add(SignupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));
        bg.add(UsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, -1));

        UsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel.setText("Username:");
        bg.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Password:");
        bg.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));
        bg.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 170, -1));

        ConfirmPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPasswordLabel.setText("Confirm Password:");
        bg.add(ConfirmPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));
        bg.add(ConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, -1));

        QuestionLabel.setForeground(new java.awt.Color(255, 255, 255));
        QuestionLabel.setText("Have an account?");
        bg.add(QuestionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        LoginLabel2.setForeground(new java.awt.Color(0, 102, 255));
        LoginLabel2.setText("Login");
        LoginLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginLabel2MouseClicked(evt);
            }
        });
        bg.add(LoginLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));
        bg.add(EmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 170, -1));

        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("Email Address:");
        EmailLabel.setToolTipText("");
        bg.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(567, 382));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        // Getting the text field for the username, password and confirm passwords
        String username = UsernameTextField.getText();
        String email = EmailTextField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        String confirmedPassword = String.valueOf(ConfirmPasswordField.getPassword());
        
        // Validation for username and password
        if (username.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a username", "Notesful Error",1);
        } else if (email.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a email", "Notesful Error",1);
        } else if (password.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a password", "Notesful Error",1);
        } else if (!confirmedPassword.equals(password)){
            JOptionPane.showMessageDialog(null, "Invalid input, password must be the same.", "Notesful Error",1);
        } else {
            try {
                userSignup(username, email, password);
            } catch (DBException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void LoginLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginLabel2MouseClicked
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        lf.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_LoginLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel LoginLabel2;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel QuestionLabel;
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel SignupLabel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JPanel bg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void userSignup(String username, String email, String password) throws DBException {
        Connection connection = DBUtil.getConnection();
        if (connection != null){
            try {
                PreparedStatement ps = (PreparedStatement) connection.prepareStatement("INSERT INTO user (Username, Email, Password) VALUES (?,?,?)");
                ps.setString(1, username);
                ps.setString(2, email);
                ps.setString(3, password);
                int rs = ps.executeUpdate();
                if (rs != 0){
                    this.dispose();
                    LoginForm lf = new LoginForm();
                    lf.setVisible(true);
                    lf.pack();
                    lf.setLocationRelativeTo(null);
                    lf.setDefaultCloseOperation(EXIT_ON_CLOSE);
                } else {
                    JOptionPane.showMessageDialog(null, "Account already exist, please login.");
                }

            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Failed to connection to database");
        }
    }
}
